In [2]:
import pandas as pd
import numpy as np
import warnings
from IPython.core.display import Image
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
warnings.filterwarnings(action="ignore")



In [3]:
#read Original data
iris=pd.read_csv("../data/Iris.csv",encoding="utf-8")
#label data
labels=iris["Species"]

#make dataFrame store predict result
samples=pd.DataFrame(index=np.arange(10),columns=np.arange(len(iris)));
#store file_name
file_name=["../data/Iris_bagging_dataset (1).csv",
           "../data/Iris_bagging_dataset (2).csv",
           "../data/Iris_bagging_dataset (3).csv",
           "../data/Iris_bagging_dataset (4).csv",
           "../data/Iris_bagging_dataset (5).csv",
           "../data/Iris_bagging_dataset (6).csv",
           "../data/Iris_bagging_dataset (7).csv",
           "../data/Iris_bagging_dataset (8).csv",
           "../data/Iris_bagging_dataset (9).csv",
           "../data/Iris_bagging_dataset (10).csv",]

In [4]:
#Load bagging data and make decision tree
def Load(i):
    #read data
    sample=pd.read_csv(file_name[i],encoding="utf-8")
    X=sample.iloc[:,1:5]
    Y=sample.iloc[:,5]
    #make decisionTree model using DecisionTreeClassifier(entropy) then learn with sample data
    tree1=tree.DecisionTreeClassifier(criterion="entropy",random_state=0,max_depth=1).fit(X,Y)
    #label is predict original data
    label=tree1.predict(iris.iloc[:,1:5])
    
    #store result into samples
    for j in range(len(iris)):
        samples.iat[i,j]=label[j]
    

In [5]:
#function count- return max index    
def Count(column):
    #elements, count is unique elements and value of count
    elements,count=np.unique(column,return_counts=True)
    max_value=count[0]
    max_index=0
    for i in range(3):
        if max_value<count[i]:
            max_value=count[i]
            max_index=i
    #reutn max elements        
    return elements[max_index]



In [6]:
#Voting it is determine what is final predict
def Voting():
    final_result=[]#store final_result(predict)
    for i in range(150):
        final_result.append(Count(samples.iloc[:,i]))
    return final_result


In [7]:
#call fucntion
for i in range(10):
    Load(i)
final_result=Voting()
#confusion_matrix and caculate precision
print(confusion_matrix(labels,final_result))
print(classification_report(labels,final_result))


[[50  0  0]
 [ 0 48  2]
 [ 0  5 45]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       0.91      0.96      0.93        50
 Iris-virginica       0.96      0.90      0.93        50

       accuracy                           0.95       150
      macro avg       0.95      0.95      0.95       150
   weighted avg       0.95      0.95      0.95       150

